---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkFunction
metadata:
  name: cnf-wan-mpls-1-edge3
  namespace: namla-system
spec:
  address: 10.25.12.230/24
  ifname: ens5
  nodename: edge3
  nvni-name: nvni-2
  type: WAN
  control-plane:
    bgp-as: 64513
---
# apiVersion: cnf.namla.com/v1alpha1
# kind: CloudNativeNetworkFunction
# metadata:
#   name: cnf-lan-lan-2-edge3
#   namespace: namla-system
# spec:
#   address: 10.25.22.28/24
#   ifname: ens4
#   nodename: edge3
#   nvni-name: nvni-1
#   type: LAN
#   #stn: true
#   control-plane:
#     bgp-as: 64514
# ---
# apiVersion: cnf.namla.com/v1alpha1
# kind: CloudNativeNetworkControllerVpnProfile
# metadata:
#   name: cnf-vpn-profile-cnf-wan-mpls-1-edge1
#   namespace: namla-system
# spec:
#   nodename: edge1
#   cnf: cnf-wan-mpls-1-edge1
#   config:
#     controllerId:
#       id: controllercnf@namla.cloud
#       type: RFC822_ADDR
#     controllerIpAddress: 51.79.100.191
#     localId:
#       id: cnf-wan-mpls-1-edge1_edge1@namla.cloud
#       type: RFC822_ADDR
#     authentication:
#       type: psk
#       name: controller1-cnf
#       key: password
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-default-route-cnf-wan-mpls-1-edge3
  namespace: namla-system
spec:
  nodename: edge3
  cnf: cnf-wan-mpls-1-edge3
  config:
    scope: GLOBAL
    dst_network: 0.0.0.0/0
    gw_addr: 10.25.12.1
    metric: 0